services:
  infrastructure.command.import_stations:
    class: NsReisplanner\Infrastructure\Command\ImportStationsCommand
    arguments:
      - '@infrastructure.repository.station'
      - '@infrastructure.read_model.repository.station.api'
    tags:
      - { name: console.command }

  infrastructure.command.import_disruptions:
    class: NsReisplanner\Infrastructure\Command\ImportDisruptionsCommand
    arguments:
      - '@infrastructure.read_model.repository.disruption.api'
      - '@infrastructure.repository.disruption'
    tags:
      - { name: console.command }
